language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements-dev.txt
script:
- bandit --exclude /tests -r .
- flake8 .
- pytest -vvvvv --cov=data_utils --cov-fail-under=80